### ISSUE TITLE
El Capitan & Dynamic Libraries

### ISSUE THREAD

**Issue by elbamos** [andersbll/cudarray#33]
I get this when I try to run the test script:

CUDArray: Failed to load CUDA back-end.
Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    import cudarray as ca
  File "redacted/lib/python2.7/site-packages/cudarray-0.1.dev0-py2.7-macosx-10.5-x86_64.egg/cudarray/__init__.py", line 20, in <module>
    from .cudarray import *
  File "redacted/lib/python2.7/site-packages/cudarray-0.1.dev0-py2.7-macosx-10.5-x86_64.egg/cudarray/cudarray.py", line 2, in <module>
    from .wrap.array_data import ArrayData
ImportError: dlopen(redacted/lib/python2.7/site-packages/cudarray-0.1.dev0-py2.7-macosx-10.5-x86_64.egg/cudarray/wrap/array_data.so, 2): Library not loaded: @rpath/libcudart.7.5.dylib
  Referenced from: redacted/lib/python2.7/site-packages/cudarray-0.1.dev0-py2.7-macosx-10.5-x86_64.egg/cudarray/wrap/array_data.so
  Reason: image not found

I suspect the cause is, in OS X El Capitan, its no longer possible to set DYLD_FALLBACK_LIBRARY_PATH or its friends.  (Well, if it is possible, it now required additional hoops.)

**Comment by elbamos** [comment]
With all of cuda/lib linked from /usr/local/lib, I get this from test.py, which one suspects would be related to the issue above:

True
Traceback (most recent call last):
  File "examples/test.py", line 493, in <module>
    run()
  File "examples/test.py", line 483, in run
    test_binary()
  File "examples/test.py", line 257, in test_binary
    c_ca = ca.divide(a_ca, b_ca)
  File "/Volumes/home500/anaconda/envs/amos27/lib/python2.7/site-packages/cudarray-0.1.dev0-py2.7-macosx-10.5-x86_64.egg/cudarray/elementwise.py", line 173, in divide
    return binary(elementwise.div_op, x1, x2, out)
  File "/Volumes/home500/anaconda/envs/amos27/lib/python2.7/site-packages/cudarray-0.1.dev0-py2.7-macosx-10.5-x86_64.egg/cudarray/elementwise.py", line 153, in binary
    'Broadcast of non-commutative operations not supported'
NotImplementedError: Broadcast of non-commutative operations not supported

**Comment by andersbll** [comment]
Better late than never! :)

Your installation is working. The last error is caused by CUDArray lacking broadcasting support for some operations in some rare cases. It should be easy to add - I just haven't needed that functionality yet.

**Comment by nresnick** [comment]
@elbamos Did you figure this out? Getting the original error you posted. Tried setting DYLD_FALLBACK_LIBRARY_PATH  as well with no luck.

**Comment by elbamos** [comment]
No, I ended up forking a torch implementation of neural style.
