### ISSUE TITLE
Install issue on Mac OS X

### ISSUE THREAD

**Issue by ym920823** [andersbll/cudarray#34]
Hi, I have tried to install it on my macbook without CUDA back-end
but I have an error message like "ImportError: No module named _build_utils.apple_accelerate"
Can you help me solve it?

The whole message is shown below

---

running install
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing requirements to cudarray.egg-info/requires.txt
writing cudarray.egg-info/PKG-INFO
writing top-level names to cudarray.egg-info/top_level.txt
writing dependency_links to cudarray.egg-info/dependency_links.txt
reading manifest file 'cudarray.egg-info/SOURCES.txt'
writing manifest file 'cudarray.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.10-intel/egg
running install_lib
running build_py
running build_ext
creating build/bdist.macosx-10.10-intel/egg
creating build/bdist.macosx-10.10-intel/egg/cudarray
copying build/lib.macosx-10.10-intel-2.7/cudarray/__init__.py -> build/bdist.macosx-10.10-intel/egg/cudarray
copying build/lib.macosx-10.10-intel-2.7/cudarray/base.py -> build/bdist.macosx-10.10-intel/egg/cudarray
creating build/bdist.macosx-10.10-intel/egg/cudarray/batch
copying build/lib.macosx-10.10-intel-2.7/cudarray/batch/__init__.py -> build/bdist.macosx-10.10-intel/egg/cudarray/batch
copying build/lib.macosx-10.10-intel-2.7/cudarray/batch/linalg.py -> build/bdist.macosx-10.10-intel/egg/cudarray/batch
copying build/lib.macosx-10.10-intel-2.7/cudarray/cudarray.py -> build/bdist.macosx-10.10-intel/egg/cudarray
copying build/lib.macosx-10.10-intel-2.7/cudarray/elementwise.py -> build/bdist.macosx-10.10-intel/egg/cudarray
creating build/bdist.macosx-10.10-intel/egg/cudarray/extra
copying build/lib.macosx-10.10-intel-2.7/cudarray/extra/__init__.py -> build/bdist.macosx-10.10-intel/egg/cudarray/extra
copying build/lib.macosx-10.10-intel-2.7/cudarray/extra/array.py -> build/bdist.macosx-10.10-intel/egg/cudarray/extra
copying build/lib.macosx-10.10-intel-2.7/cudarray/helpers.py -> build/bdist.macosx-10.10-intel/egg/cudarray
copying build/lib.macosx-10.10-intel-2.7/cudarray/linalg.py -> build/bdist.macosx-10.10-intel/egg/cudarray
creating build/bdist.macosx-10.10-intel/egg/cudarray/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/nnet/__init__.py -> build/bdist.macosx-10.10-intel/egg/cudarray/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/nnet/conv.py -> build/bdist.macosx-10.10-intel/egg/cudarray/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/nnet/image.py -> build/bdist.macosx-10.10-intel/egg/cudarray/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/nnet/math.py -> build/bdist.macosx-10.10-intel/egg/cudarray/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/nnet/pool.py -> build/bdist.macosx-10.10-intel/egg/cudarray/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/nnet/special.py -> build/bdist.macosx-10.10-intel/egg/cudarray/nnet
creating build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend
copying build/lib.macosx-10.10-intel-2.7/cudarray/numpy_backend/__init__.py -> build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend
creating build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/numpy_backend/nnet/__init__.py -> build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/numpy_backend/nnet/activations.py -> build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/numpy_backend/nnet/conv.py -> build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/numpy_backend/nnet/conv_bc01.so -> build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/numpy_backend/nnet/lrnorm_bc01.so -> build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/numpy_backend/nnet/pool.py -> build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/numpy_backend/nnet/pool_bc01.so -> build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/numpy_backend/nnet/special.py -> build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet
copying build/lib.macosx-10.10-intel-2.7/cudarray/random.py -> build/bdist.macosx-10.10-intel/egg/cudarray
copying build/lib.macosx-10.10-intel-2.7/cudarray/reduction.py -> build/bdist.macosx-10.10-intel/egg/cudarray
creating build/bdist.macosx-10.10-intel/egg/cudarray/wrap
copying build/lib.macosx-10.10-intel-2.7/cudarray/wrap/__init__.py -> build/bdist.macosx-10.10-intel/egg/cudarray/wrap
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/base.py to base.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/batch/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/batch/linalg.py to linalg.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/cudarray.py to cudarray.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/elementwise.py to elementwise.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/extra/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/extra/array.py to array.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/helpers.py to helpers.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/linalg.py to linalg.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/nnet/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/nnet/conv.py to conv.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/nnet/image.py to image.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/nnet/math.py to math.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/nnet/pool.py to pool.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/nnet/special.py to special.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet/activations.py to activations.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet/conv.py to conv.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet/pool.py to pool.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet/special.py to special.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/random.py to random.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/reduction.py to reduction.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/wrap/__init__.py to __init__.pyc
creating stub loader for cudarray/numpy_backend/nnet/conv_bc01.so
creating stub loader for cudarray/numpy_backend/nnet/pool_bc01.so
creating stub loader for cudarray/numpy_backend/nnet/lrnorm_bc01.so
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet/conv_bc01.py to conv_bc01.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet/pool_bc01.py to pool_bc01.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/cudarray/numpy_backend/nnet/lrnorm_bc01.py to lrnorm_bc01.pyc
creating build/bdist.macosx-10.10-intel/egg/EGG-INFO
copying cudarray.egg-info/PKG-INFO -> build/bdist.macosx-10.10-intel/egg/EGG-INFO
copying cudarray.egg-info/SOURCES.txt -> build/bdist.macosx-10.10-intel/egg/EGG-INFO
copying cudarray.egg-info/dependency_links.txt -> build/bdist.macosx-10.10-intel/egg/EGG-INFO
copying cudarray.egg-info/not-zip-safe -> build/bdist.macosx-10.10-intel/egg/EGG-INFO
copying cudarray.egg-info/requires.txt -> build/bdist.macosx-10.10-intel/egg/EGG-INFO
copying cudarray.egg-info/top_level.txt -> build/bdist.macosx-10.10-intel/egg/EGG-INFO
writing build/bdist.macosx-10.10-intel/egg/EGG-INFO/native_libs.txt
creating 'dist/cudarray-0.1.dev-py2.7-macosx-10.10-intel.egg' and adding 'build/bdist.macosx-10.10-intel/egg' to it
removing 'build/bdist.macosx-10.10-intel/egg' (and everything under it)
Processing cudarray-0.1.dev-py2.7-macosx-10.10-intel.egg
removing '/Library/Python/2.7/site-packages/cudarray-0.1.dev-py2.7-macosx-10.10-intel.egg' (and everything under it)
creating /Library/Python/2.7/site-packages/cudarray-0.1.dev-py2.7-macosx-10.10-intel.egg
Extracting cudarray-0.1.dev-py2.7-macosx-10.10-intel.egg to /Library/Python/2.7/site-packages
cudarray 0.1.dev is already the active version in easy-install.pth

Installed /Library/Python/2.7/site-packages/cudarray-0.1.dev-py2.7-macosx-10.10-intel.egg
Processing dependencies for cudarray==0.1.dev
Searching for numpy>=1.8
Reading https://pypi.python.org/simple/numpy/
Best match: numpy 1.10.1
Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.10.1.zip#md5=6f57c58bc5b28440fbeccd505da63d58
Processing numpy-1.10.1.zip
Writing /tmp/easy_install-0FU_YO/numpy-1.10.1/setup.cfg
Running numpy-1.10.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0FU_YO/numpy-1.10.1/egg-dist-tmp-TgA5CX
Warning: distutils distribution has been initialized, it may be too late to add a subpackage compatTraceback (most recent call last):
  File "setup.py", line 161, in <module>
    zip_safe=False,
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 374, in run
    self.easy_install(spec, not self.no_deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 590, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 641, in install_item
    self.process_distribution(spec, dist, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 687, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 568, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 806, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 818, in obtain
    return installer(requirement)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 609, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 639, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 825, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1031, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1016, in run_setup
    run_setup(setup_script, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 69, in run_setup
    lambda: execfile(
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 120, in run
    return func()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 71, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 264, in <module>

  File "setup.py", line 256, in setup_package

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 156, in configuration
    },
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy/setup.py", line 11, in configuration
    from Cython.Distutils.extension import Extension
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/misc_util.py", line 847, in _get_configuration_from_setup_py
    ('.py', 'U', 1))
  File "/private/tmp/easy_install-0FU_YO/numpy-1.10.1/numpy/core/setup.py", line 13, in <module>

ImportError: No module named _build_utils.apple_accelerate

**Comment by andersbll** [comment]
Sorry about the late reply! It seems to me that NumPy fails to install. Maybe you should try another Python distribution, e.g. Anaconda Python.

**Comment by nresnick** [comment]
I'm having this issue as well, how would i go about trying the anaconda distribution?

**Comment by andersbll** [comment]
OS X installers are available on their website: https://www.continuum.io/downloads

**Comment by ym920823** [comment]
Hi, i think i fix this problem with updating my numpy package
