### ISSUE TITLE
install codecs issue . UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 14: ordinal not in range(128)

### ISSUE THREAD

**Issue by streamgao** [andersbll/cudarray#46]
Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    ext_modules=numpy_extensions(),
  File "setup.py", line 79, in numpy_extensions
    return cythonize(cython_srcs, include_path=[numpy.get_include()])
  File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 758, in cythonize
    aliases=aliases)
  File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 664, in create_extension_list
    kwds = deps.distutils_info(file, aliases, base).values
  File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 564, in distutils_info
    return (self.transitive_merge(filename, self.distutils_info0, DistutilsInfo.merge)
  File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 574, in transitive_merge
    node, extract, merge, seen, {}, self.cimported_files)[0]
  File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 585, in transitive_merge_helper
    for next in outgoing(node):
  File "/usr/local/lib/python2.7/site-packages/Cython/Utils.py", line 43, in wrapper
    res = cache[args] = f(self, *args)
  File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 513, in cimported_files
    pxd_file = self.find_pxd(module, filename)
  File "/usr/local/lib/python2.7/site-packages/Cython/Utils.py", line 43, in wrapper
    res = cache[args] = f(self, *args)
  File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 497, in find_pxd
    pxd = self.context.find_pxd_file(relative, None)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 239, in find_pxd_file
    pxd = self.search_include_directories(qualified_name, ".pxd", pos, sys_path=sys_path)
  File "/usr/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 280, in search_include_directories
    tuple(self.include_directories), qualified_name, suffix, pos, include, sys_path)
  File "/usr/local/lib/python2.7/site-packages/Cython/Utils.py", line 29, in wrapper
    res = cache[args] = f(*args)
  File "/usr/local/lib/python2.7/site-packages/Cython/Utils.py", line 119, in search_include_directories
    path = os.path.join(dir, dotted_filename)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 14: ordinal not in range(128)

**Comment by andersbll** [comment]
Hi, could it be that your working directory contains an invalid character?

**Comment by streamgao** [comment]
Yes ! I moved the folder and it worked!
Thanks!
