### ISSUE TITLE
Ubuntu 14.04 cuda7.5 cudnn 5.1 Anaconda2.7 install problem

### ISSUE THREAD

**Issue by filmo** [andersbll/cudarray#64]
I'm recently updated my cudnn to 5.1 and thought to recompile cudarray. In hindsight this might not have been needed, but now I've seem to have broken my install. (It was working before.)

I've got CUDA 7.5 installed correctly in /usr/local/cuda and my environmental variables are correctly set as per the README file. 

I did
```
make
make install
python setup.py install
```

Results here: https://gist.github.com/filmo/0821af03f01da8592e09921953b4ae5a
Seems like it correctly compiled to me and installed correctly in my anaconda lib/python2.7/site-packages folder, but perhaps not ??? (I see the cudarray-0.1.dev0-py2.7-linux-x86_64.egg in that folder.)

However when I now try to import inside of Python I'm seeing the following:

```
philglau (master *) cudarray $ python
Python 2.7.12 |Anaconda 2.4.1 (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import cudarray as ca
CUDArray: CUDA back-end not available, using NumPy.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cudarray/__init__.py", line 40, in <module>
    from .numpy_backend import *
  File "cudarray/numpy_backend/__init__.py", line 2, in <module>
    from .nnet import *
  File "cudarray/numpy_backend/nnet/__init__.py", line 3, in <module>
    from .conv_bc01 import *
ImportError: No module named conv_bc01
```

If I list the folder reference in the error message, I see conv_bc01
```
philglau nnet $ ls
activations.py   conv_bc01.py   conv_bc01.so  conv.pyc     __init__.pyc    lrnorm_bc01.pyc  pool_bc01.py   pool_bc01.so  pool.pyc    special.pyc
activations.pyc  conv_bc01.pyc  conv.py       __init__.py  lrnorm_bc01.py  lrnorm_bc01.so   pool_bc01.pyc  pool.py       special.py
philglau nnet $ 
```

Any pointers on where I might have gone wrong?

**Comment by andersbll** [comment]
Try `make clean` and `python setup.py clean` before building.
