### ISSUE TITLE
ValueError: an illegal memory access was encountered

### ISSUE THREAD

**Issue by ghost** [andersbll/cudarray#82]
Hello mates,

I open an issue to help people having trouble with using `./neural_artistic_style.py` 

Error:
Traceback (most recent call last):
  File "neural_artistic_style.py", line 137, in <module>
    run()
....
  File "cudarray/wrap/array_data.pyx", line 16, in cudarray.wrap.array_data.ArrayData.__init__
  File "cudarray/wrap/cudart.pyx", line 12, in cudarray.wrap.cudart.cudaCheck
ValueError: an illegal memory access was encountered
terminate called after throwing an instance of 'std::runtime_error'
  what():  ./include/cudarray/common.hpp:95: an illegal memory access was encountered
Abandon (core dumped)

`----`
There is something wrong with "sum" function, I suppose that is an error in `reduction.cpp` or `reduction.py` (cython?)

**Comment by ghost** [comment]
ca.dot, problem too
